import { app, BrowserWindow } from 'electron';
import * as fs from 'fs';
import * as path from 'path';
import { registerRaportIpc } from './main/raportIpc';
import { disposePrisma, getPrisma } from './main/raportDb';
import { autoFixResourcesOnStartup } from './main/resourcesAutoFix';
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

function isSemverDirName(name: string): boolean {
  return /^app-\d+\.\d+\.\d+(?:[-+].+)?$/i.test(String(name || '').trim());
}

function getSquirrelInstallRoot(): { root: string; currentAppDir: string | null } | null {
  if (process.platform !== 'win32') return null;
  if (!app.isPackaged) return null;

  const exeDir = path.dirname(process.execPath);
  const base = path.basename(exeDir);

  // Typical: %LOCALAPPDATA%\<app>\app-x.y.z\<exe>
  if (isSemverDirName(base)) {
    return { root: path.dirname(exeDir), currentAppDir: base };
  }

  // Fallback: sometimes process.execPath is the root stub: %LOCALAPPDATA%\<app>\<exe>
  return { root: exeDir, currentAppDir: null };
}

function cleanupOldSquirrelAppDirs() {
  const ctx = getSquirrelInstallRoot();
  if (!ctx) return;

  const { root } = ctx;
  const currentAppDir = ctx.currentAppDir ?? `app-${app.getVersion()}`;

  try {
    if (!fs.existsSync(path.join(root, 'Update.exe'))) return;
  } catch {
    return;
  }

  let entries: fs.Dirent[] = [];
  try {
    entries = fs.readdirSync(root, { withFileTypes: true });
  } catch {
    return;
  }

  for (const e of entries) {
    if (!e.isDirectory()) continue;
    if (!isSemverDirName(e.name)) continue;
    if (e.name === currentAppDir) continue;

    try {
      fs.rmSync(path.join(root, e.name), { recursive: true, force: true, maxRetries: 3 });
    } catch {
      // ignore (e.g. files still locked)
    }
  }
}

function resolveAppIconPath(): string | undefined {
  const candidates: string[] = [];
  if (!app.isPackaged) {
    candidates.push(path.resolve(process.cwd(), 'resources', 'icon.ico'));
    candidates.push(path.resolve(__dirname, '..', 'resources', 'icon.ico'));
  } else {
    candidates.push(path.resolve(app.getPath('userData'), 'resources', 'icon.ico'));
    candidates.push(path.resolve(process.resourcesPath, 'resources', 'icon.ico'));
    candidates.push(path.resolve(process.resourcesPath, 'icon.ico'));
  }

  for (const p of candidates) {
    try {
      if (fs.existsSync(p)) return p;
    } catch {
      // ignore
    }
  }
  return undefined;
}

const createWindow = (): void => {
  // Create the browser window.
  const iconPath = resolveAppIconPath();
  const mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    minHeight: 640,
    minWidth: 900,
    ...(iconPath ? { icon: iconPath } : {}),
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  if (!app.isPackaged) {
    mainWindow.webContents.openDevTools();
  }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  registerRaportIpc();
  void autoFixResourcesOnStartup().catch(() => {});
  void getPrisma().catch(() => {});
  createWindow();

  // Squirrel leaves old app-* folders for rollback; we prefer disk cleanup.
  setTimeout(() => cleanupOldSquirrelAppDirs(), 5000);
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.on('before-quit', async () => {
  await disposePrisma();
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
