export type RaportColumn = {
  field: string;
  label: string;
};

export const RAPORT_COLUMNS: ReadonlyArray<RaportColumn> = [
  { field: "oddzial", label: "Oddział" },
  { field: "nr_sad", label: "Nr SAD" },
  { field: "numer_pozycji", label: "Numer pozycji" },
  { field: "rodzaj_sad", label: "Rodzaj SAD" },
  { field: "typ_sad_u", label: "Typ SAD-u" },
  { field: "data_sad_p_54", label: "Data SAD (p.54)" },
  { field: "data_mrn", label: "Data MRN" },
  { field: "stan", label: "Stan" },
  { field: "numer_mrn", label: "Numer MRN" },
  { field: "numer_pwd", label: "Numer PWD" },
  { field: "numer_mrn_uzupeln", label: "Numer MRN uzupełn." },
  { field: "data_mrn_uzupeln", label: "Data MRN uzupełn." },
  { field: "eksporter", label: "Eksporter" },
  { field: "odbiorca", label: "Odbiorca" },
  { field: "kraj_wysylki", label: "Kraj wysyłki" },
  { field: "numer_samochodu", label: "Numer samochodu" },
  { field: "warunki_dostawy", label: "Warunki dostawy" },
  { field: "wartosc_faktury", label: "Wartość faktury" },
  { field: "waluta", label: "Waluta" },
  { field: "kurs_waluty", label: "Kurs waluty" },
  { field: "transport_na_granicy_rodzaj", label: "Transport na granicy - rodzaj" },
  { field: "transport_na_granicy_znaki", label: "Transport na granicy - znaki" },
  { field: "opis_towaru", label: "Opis towaru" },
  { field: "typ_opakowan", label: "Typ opakowań" },
  { field: "liczba_opakowan", label: "Liczba opakowań" },
  { field: "znaki_opakowania", label: "Znaki opakowania" },
  { field: "ilosc_w_uzup_j_m", label: "Ilość w uzup. j.m." },
  { field: "numer_kontenera", label: "Numer kontenera" },
  { field: "kod_towaru", label: "Kod towaru" },
  { field: "kraj_pochodzenia", label: "Kraj pochodzenia" },
  { field: "preferencje", label: "Preferencje" },
  { field: "procedura", label: "Procedura" },
  { field: "numer_faktury", label: "Numer faktury" },
  { field: "data_fakt", label: "Data fakt" },
  { field: "wartosc_pozycji", label: "Wartość pozycji" },
  { field: "wartosc_statystyczna", label: "Wartość statystyczna" },
  { field: "zglaszajacy", label: "Zgłaszający" },
  { field: "oplaty_celne_razem", label: "Opłaty celne razem" },
  { field: "towary", label: "Towary" },
  { field: "nr_konosamentu", label: "Nr konosamentu" },
  { field: "typ_konosamentu", label: "Typ konosamentu" },
  { field: "masa_netto", label: "Masa netto" },
  { field: "masa_brutto", label: "Masa brutto" },
  { field: "numer_dokumentu_n703", label: "Numer dokumentu N703" },
  { field: "numery_mrn_p_40", label: "Numery MRN p.40" },
  { field: "numery_dsk_p_40", label: "Numery DSK p.40" },
  { field: "dokumenty_z_opcji_1", label: "Dokumenty z opcji 1" },
  { field: "dokumenty_z_opcji_2", label: "Dokumenty z opcji 2" },
  { field: "wykaz_kont", label: "Wykaz kont." },
  { field: "kody_dod_pl", label: "Kody dod. PL" },
  { field: "kody_dod_eu", label: "Kody dod. EU" },
  { field: "podstawa_vat", label: "Podstawa VAT" },
  { field: "podstawa_akcyzy", label: "Podstawa akcyzy" },
  { field: "data_wpisu_rpu", label: "Data wpisu RPU" },
  { field: "nr_rpu_zglosz", label: "Nr RPU (zgłosz.)" },
  { field: "nr_rpu_tow", label: "Nr RPU (tow.)" },
  { field: "numer_pozwolenia_c601_c516_c019_n990", label: "Numer pozwolenia (C601/C516/C019/N990)”" },
  { field: "jednostka_wg_pozwolenia", label: "Jednostka wg pozwolenia" },
  { field: "ilosc_wg_pozwolenia", label: "Ilość wg pozwolenia" },
  { field: "rodzaj_zglaszajacego", label: "Rodzaj zgłaszającego" },
  { field: "numer_cmr", label: "Numer CMR" },
  { field: "numer_dokumentu_2dk9", label: "Numer dokumentu 2DK9" },
  { field: "dodatkowe_odniesienia", label: "Dodatkowe odniesienia" },
  { field: "ilosc_z_pola_31", label: "Ilość z pola 31" },
  { field: "jm_z_pola_31", label: "JM z pola 31" },
  { field: "c_1a1_podstawa", label: "1A1 podstawa" },
  { field: "c_1a1_stawka", label: "1A1 stawka" },
  { field: "c_1a1_kwota", label: "1A1 kwota" },
  { field: "c_1a1_mp", label: "1A1 MP" },
  { field: "c_1p1_podstawa", label: "1P1 podstawa" },
  { field: "c_1p1_stawka", label: "1P1 stawka" },
  { field: "c_1p1_kwota", label: "1P1 kwota" },
  { field: "c_1p1_mp", label: "1P1 MP" },
  { field: "c_1r1_podstawa", label: "1R1 podstawa" },
  { field: "c_1r1_stawka", label: "1R1 stawka" },
  { field: "c_1r1_kwota", label: "1R1 kwota" },
  { field: "c_1r1_mp", label: "1R1 MP" },
  { field: "c_1s1_podstawa", label: "1S1 podstawa" },
  { field: "c_1s1_stawka", label: "1S1 stawka" },
  { field: "c_1s1_kwota", label: "1S1 kwota" },
  { field: "c_1s1_mp", label: "1S1 MP" },
  { field: "c_1t1_podstawa", label: "1T1 podstawa" },
  { field: "c_1t1_stawka", label: "1T1 stawka" },
  { field: "c_1t1_kwota", label: "1T1 kwota" },
  { field: "c_1t1_mp", label: "1T1 MP" },
  { field: "c_1z1_podstawa", label: "1Z1 podstawa" },
  { field: "c_1z1_stawka", label: "1Z1 stawka" },
  { field: "c_1z1_kwota", label: "1Z1 kwota" },
  { field: "c_1z1_mp", label: "1Z1 MP" },
  { field: "a00_podstawa", label: "A00 podstawa" },
  { field: "a00_stawka", label: "A00 stawka" },
  { field: "a00_kwota", label: "A00 kwota" },
  { field: "a00_mp", label: "A00 MP" },
  { field: "a20_podstawa", label: "A20 podstawa" },
  { field: "a20_stawka", label: "A20 stawka" },
  { field: "a20_kwota", label: "A20 kwota" },
  { field: "a20_mp", label: "A20 MP" },
  { field: "a30_podstawa", label: "A30 podstawa" },
  { field: "a30_stawka", label: "A30 stawka" },
  { field: "a30_kwota", label: "A30 kwota" },
  { field: "a30_mp", label: "A30 MP" },
  { field: "a35_podstawa", label: "A35 podstawa" },
  { field: "a35_stawka", label: "A35 stawka" },
  { field: "a35_kwota", label: "A35 kwota" },
  { field: "a35_mp", label: "A35 MP" },
  { field: "a40_podstawa", label: "A40 podstawa" },
  { field: "a40_stawka", label: "A40 stawka" },
  { field: "a40_kwota", label: "A40 kwota" },
  { field: "a40_mp", label: "A40 MP" },
  { field: "a45_podstawa", label: "A45 podstawa" },
  { field: "a45_stawka", label: "A45 stawka" },
  { field: "a45_kwota", label: "A45 kwota" },
  { field: "a45_mp", label: "A45 MP" },
  { field: "b00_podstawa", label: "B00 podstawa" },
  { field: "b00_stawka", label: "B00 stawka" },
  { field: "b00_kwota", label: "B00 kwota" },
  { field: "b00_mp", label: "B00 MP" },
  { field: "b10_podstawa", label: "B10 podstawa" },
  { field: "b10_stawka", label: "B10 stawka" },
  { field: "b10_kwota", label: "B10 kwota" },
  { field: "b10_mp", label: "B10 MP" },
  { field: "b20_podstawa", label: "B20 podstawa" },
  { field: "b20_stawka", label: "B20 stawka" },
  { field: "b20_kwota", label: "B20 kwota" },
  { field: "b20_mp", label: "B20 MP" },
  { field: "c00_podstawa", label: "C00 podstawa" },
  { field: "c00_stawka", label: "C00 stawka" },
  { field: "c00_kwota", label: "C00 kwota" },
  { field: "c00_mp", label: "C00 MP" },
  { field: "c10_podstawa", label: "C10 podstawa" },
  { field: "c10_stawka", label: "C10 stawka" },
  { field: "c10_kwota", label: "C10 kwota" },
  { field: "c10_mp", label: "C10 MP" },
  { field: "d00_podstawa", label: "D00 podstawa" },
  { field: "d00_stawka", label: "D00 stawka" },
  { field: "d00_kwota", label: "D00 kwota" },
  { field: "d00_mp", label: "D00 MP" },
  { field: "d10_podstawa", label: "D10 podstawa" },
  { field: "d10_stawka", label: "D10 stawka" },
  { field: "d10_kwota", label: "D10 kwota" },
  { field: "d10_mp", label: "D10 MP" },
  { field: "e00_podstawa", label: "E00 podstawa" },
  { field: "e00_stawka", label: "E00 stawka" },
  { field: "e00_kwota", label: "E00 kwota" },
  { field: "e00_mp", label: "E00 MP" },
  { field: "c_001w_kwota", label: "001W kwota" },
  { field: "c_002w_kwota", label: "002W kwota" },
  { field: "c_003w_kwota", label: "003W kwota" },
  { field: "c_004w_kwota", label: "004W kwota" },
  { field: "c_005w_kwota", label: "005W kwota" },
  { field: "c_006w_kwota", label: "006W kwota" },
  { field: "c_007w_kwota", label: "007W kwota" },
  { field: "c_008w_kwota", label: "008W kwota" },
  { field: "c_009w_kwota", label: "009W kwota" },
  { field: "c_010w_kwota", label: "010W kwota" },
  { field: "c_020w_kwota", label: "020W kwota" },
  { field: "c_021w_kwota", label: "021W kwota" },
  { field: "c_022w_kwota", label: "022W kwota" },
  { field: "c_023w_kwota", label: "023W kwota" },
  { field: "c_024w_kwota", label: "024W kwota" },
  { field: "c_025w_kwota", label: "025W kwota" },
  { field: "c_026w_kwota", label: "026W kwota" },
  { field: "c_027w_kwota", label: "027W kwota" },
  { field: "c_028w_kwota", label: "028W kwota" },
  { field: "c_029w_kwota", label: "029W kwota" },
  { field: "c_030w_kwota", label: "030W kwota" },
  { field: "c_031w_kwota", label: "031W kwota" },
  { field: "c_032w_kwota", label: "032W kwota" },
  { field: "c_033w_kwota", label: "033W kwota" },
  { field: "c_034w_kwota", label: "034W kwota" },
  { field: "c_040w_kwota", label: "040W kwota" },
  { field: "c_041w_kwota", label: "041W kwota" },
  { field: "c_042w_kwota", label: "042W kwota" },
  { field: "c_043w_kwota", label: "043W kwota" },
  { field: "c_044w_kwota", label: "044W kwota" },
  { field: "c_045w_kwota", label: "045W kwota" },
  { field: "c_046w_kwota", label: "046W kwota" },
  { field: "c_047w_kwota", label: "047W kwota" },
  { field: "c_050w_kwota", label: "050W kwota" },
  { field: "c_051w_kwota", label: "051W kwota" },
  { field: "c_052w_kwota", label: "052W kwota" },
  { field: "c_053w_kwota", label: "053W kwota" },
  { field: "c_054w_kwota", label: "054W kwota" },
  { field: "c_055w_kwota", label: "055W kwota" },
  { field: "c_056w_kwota", label: "056W kwota" },
  { field: "c_057w_kwota", label: "057W kwota" },
  { field: "c_058w_kwota", label: "058W kwota" },
  { field: "c_059w_kwota", label: "059W kwota" },
  { field: "c_071v_kwota", label: "071V kwota" },
  { field: "c_072x_kwota", label: "072X kwota" },
  { field: "c_073v_kwota", label: "073V kwota" },
  { field: "c_074a_kwota", label: "074A kwota" },
  { field: "c_080b_kwota", label: "080B kwota" },
  { field: "c_1stw_kwota", label: "1STW kwota" },
  { field: "c_2stw_kwota", label: "2STW kwota" },
  { field: "ab_kwota", label: "AB kwota" },
  { field: "ad_kwota", label: "AD kwota" },
  { field: "ae_kwota", label: "AE kwota" },
  { field: "af_kwota", label: "AF kwota" },
  { field: "ag_kwota", label: "AG kwota" },
  { field: "ah_kwota", label: "AH kwota" },
  { field: "ai_kwota", label: "AI kwota" },
  { field: "aj_kwota", label: "AJ kwota" },
  { field: "ak_kwota", label: "AK kwota" },
  { field: "al_kwota", label: "AL kwota" },
  { field: "an_kwota", label: "AN kwota" },
  { field: "ba_kwota", label: "BA kwota" },
  { field: "bb_kwota", label: "BB kwota" },
  { field: "bc_kwota", label: "BC kwota" },
  { field: "bd_kwota", label: "BD kwota" },
  { field: "be_kwota", label: "BE kwota" },
  { field: "bf_kwota", label: "BF kwota" },
  { field: "bg_kwota", label: "BG kwota" },
  { field: "bh_kwota", label: "BH kwota" },
  { field: "bi_kwota", label: "BI kwota" },
  { field: "komentarz", label: "Komentarz" },
  { field: "komentarz_dodatkowy", label: "Komentarz dodatkowy" },
] as const;
